// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBtVoczy_ExP44GpXhE1hB3rCfSRE_An0',
    appId: '1:180598404193:web:f82cba91be8e7c2f046620',
    messagingSenderId: '180598404193',
    projectId: 'flutter-chat-5dae2',
    authDomain: 'flutter-chat-5dae2.firebaseapp.com',
    storageBucket: 'flutter-chat-5dae2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3SsdCj6gI5G5i5X7r_wSF8k0tCCPFZWs',
    appId: '1:180598404193:android:8292586bc09b8b8a046620',
    messagingSenderId: '180598404193',
    projectId: 'flutter-chat-5dae2',
    storageBucket: 'flutter-chat-5dae2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKGRoPpk9960i74662PsLue6LQV3vEiKI',
    appId: '1:180598404193:ios:9cd3504c12c752a4046620',
    messagingSenderId: '180598404193',
    projectId: 'flutter-chat-5dae2',
    storageBucket: 'flutter-chat-5dae2.appspot.com',
    iosClientId: '180598404193-to71nou5j097l7laj2p135qo8ri3h71h.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChat',
  );
}
